Repository iansan5653/open-mcr, pull requests merged in 2021-11, with the labels that each got.

#43 Fix/grid reading in rotated images
  .gitignore
  .vscode/launch.json
  code/corner_finding.py
  code/data_exporting.py
  code/geometry_utils.py
  code/grid_reading.py
  code/image_utils.py
  code/main.py
  code/user_interface.py
  examples/issue-27/180deg.jpg
  examples/issue-27/270deg.jpg
  examples/issue-27/90deg.jpg
  typings/cv2/__init__.pyi
Labels: bug

#46 Add support for outputting files for MCTA
  code/data_exporting.py
  code/main.py
  code/mcta_processing.py
  code/user_interface.py
  examples/batch-B/11.jpg
Labels: enhancement

#47 Fix process failing to exit when the user closes
  code/main.py
  code/user_interface.py
Labels: bug

#50 Create funding.yml to enable Sponsor button
  .github/funding.yml
Labels: documentation

#54 Extract file trimming function and implement in MCTA key generation
  code/data_exporting.py
  code/list_utils.py
  code/mcta_processing.py
Labels: bug

#58 Add a CLI
  build_instructions.md
  code/main.py
  code/main_gui.py
  code/process_input.py
  readme.md
Labels: documentation, enhancement

#56 Fix startup error on Linux by only setting TKinter window icon on Windows
  code/user_interface.py
  readme.md
Labels: bug, documentation, help wanted
